### ISSUE TITLE
Merging Koa support to swagger-stats

### ISSUE THREAD

**Issue by sv2** [chong0808/swagger-stats-koa#1]
Hi @chong0808 

thinking to merge your work to swagger-stats, so it would support Koa natively ... what do you think ?

Thanks!
sv2

**Comment by chong0808** [comment]
it is a good idea。。。 but it is not write unit test and no coverage tests. I 'll rearrange the code in two days.

**Comment by dduo518** [comment]
i push my code

**Comment by sv2** [comment]
Thank you! Give me some time to review, please ...

**Comment by dduo518** [comment]
I am so sorry ! I dont know how to write unit test! very sorry!!!!!
